CREATE TABLE Questions (
    Id INT PRIMARY KEY IDENTITY,
    QuestionText NVARCHAR(512) NOT NULL,
    OptionA NVARCHAR(256) NOT NULL,
    OptionB NVARCHAR(256) NOT NULL,
    OptionC NVARCHAR(256) NOT NULL,
    OptionD NVARCHAR(256) NOT NULL,
    CorrectAnswer NVARCHAR(256) NOT NULL
);
